http:
  middlewares:
    security-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
    
    compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"
          - "application/octet-stream"
          - "image/jpeg"
          - "image/png"
          - "image/gif"
          - "application/pdf"
        minResponseBodyBytes: 1024
        encodings:
          - "br"
          - "gzip"
    
    ratelimit:
      rateLimit:
        average: 100
        burst: 50

    in-flight-limiter:
      inFlightReq:
        amount: 10

    retry:
      retry:
        attempts: 3
        initialInterval: 100ms

    latency-check:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.20 || ResponseCodeRatio(500, 600, 0, 600) > 0.25"
        checkPeriod: "10s"
        fallbackDuration: "30s"
        recoveryDuration: "60s"
        responseCode: 503